# Generated by Django 2.1.7 on 2019-02-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190216_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default='#', max_length=400),
        ),
    ]
