# Generated by Django 2.1.7 on 2019-02-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_readinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reading'), ('c', 'Completed'), ('w', 'Wish List')], default='w', help_text='Reading List', max_length=1),
        ),
    ]
