# Generated by Django 2.1.7 on 2019-02-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190217_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='buyer',
            new_name='owner',
        ),
    ]
