# Generated by Django 2.1.7 on 2019-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190218_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authored_books', to='catalog.Book'),
        ),
    ]
