# Generated by Django 2.1.7 on 2019-02-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190219_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='archive',
            field=models.BooleanField(default=False, help_text='In store'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation', to='catalog.Language'),
        ),
    ]
