# Generated by Django 2.1.7 on 2019-02-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190220_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pur_date',
        ),
    ]
